#!/bin/bash

#
# Remove  all docker containers that have exited
#
docker ps --all --quiet --no-trunc --filter "status=exited" | xargs --no-run-if-empty docker rm

#
# Remove all docker images considered "dangling"
#
docker images --quiet --filter "dangling=true" | xargs --no-run-if-empty docker rmi

