#!/bin/bash

DATESTAMP=$(date +%Y%m%d%H%M%S)
OUTPUTDIR='/root'
FILEPREFIX="snapshot_etc_$(hostname -s)"
FILENAME="${FILEPREFIX}_${DATESTAMP}.tar"

if [[ $EUID -ne 0 ]]; then
    echo
    echo 'This script must be run as root.'
    echo
    exit 1
fi


cd ${OUTPUTDIR}                 \
    && tar -cf ${FILENAME} /etc \
    && gzip -9 ${FILENAME}


NUMSNAPSHOTS=$(ls -l "${OUTPUTDIR}/${FILEPREFIX}"* | wc -l)


df -h

echo
echo "There are currently ${NUMSNAPSHOTS} snapshots in ${OUTPUTDIR}."
echo
exit $?
# vim: set expandtab smarttab tabstop=4 shiftwidth=4 softtabstop=4:
